Repository canonical/kfp-operators, pull requests merged in 2023-10, with the labels that each got.

#347 fix: explicitly set the command for schedwf pebble Layer
  charms/kfp-schedwf/src/charm.py
  charms/kfp-schedwf/src/components/pebble_component.py
Labels: Libraries: OK, Kubeflow 1.8

#344 Decorator controller rewrite
  charms/kfp-profile-controller/files/upstream/sync.py
  charms/kfp-profile-controller/src/charm.py
  charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
  charms/kfp-profile-controller/tests/integration/test_charm.py
Labels: Libraries: OK

#346 Contributing files
  charms/kfp-api/CONTRIBUTING.md
  charms/kfp-persistence/CONTRIBUTING.md
  charms/kfp-profile-controller/CONTRIBUTING.md
  charms/kfp-schedwf/CONTRIBUTING.md
  charms/kfp-ui/CONTRIBUTING.md
  charms/kfp-viewer/CONTRIBUTING.md
  charms/kfp-viz/CONTRIBUTING.md
Labels: Libraries: OK

#349 feat: add sa token component to kfp-persistence
  charms/kfp-persistence/requirements-unit.txt
  charms/kfp-persistence/requirements.in
  charms/kfp-persistence/requirements.txt
  charms/kfp-persistence/src/charm.py
  charms/kfp-persistence/src/components/sa_token_component.py
  charms/kfp-persistence/src/templates/auth_manifests.yaml.j2
  charms/kfp-persistence/tests/unit/data/persistenceagent-sa-token
  charms/kfp-persistence/tests/unit/test_operator.py
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
Labels: Libraries: OK

#350 feat: Add kfp-metadata-writer charm
  .github/workflows/integrate.yaml
  .gitignore
  charms/kfp-metadata-writer/CONTRIBUTING.md
  charms/kfp-metadata-writer/README.md
  charms/kfp-metadata-writer/charmcraft.yaml
  charms/kfp-metadata-writer/config.yaml
  charms/kfp-metadata-writer/icon.svg
  charms/kfp-metadata-writer/metadata.yaml
  charms/kfp-metadata-writer/pyproject.toml
  charms/kfp-metadata-writer/requirements-fmt.in
  charms/kfp-metadata-writer/requirements-fmt.txt
  charms/kfp-metadata-writer/requirements-lint.in
  charms/kfp-metadata-writer/requirements-lint.txt
  charms/kfp-metadata-writer/requirements-unit.in
  charms/kfp-metadata-writer/requirements-unit.txt
  charms/kfp-metadata-writer/requirements.in
  charms/kfp-metadata-writer/requirements.txt
  charms/kfp-metadata-writer/src/charm.py
  charms/kfp-metadata-writer/src/components/pebble_component.py
  charms/kfp-metadata-writer/src/templates/auth_manifests.yaml.j2
  charms/kfp-metadata-writer/tests/unit/test_operator.py
  charms/kfp-metadata-writer/tox.ini
  tests/integration/test_kfp_functional.py
  tox.ini
Labels: Libraries: OK

#353 fix: bump kfp-schedwf rock version with patch
  charms/kfp-schedwf/metadata.yaml
Labels: Libraries: Out of sync

#358 fix: add correct SA name to CRB
  charms/kfp-persistence/src/templates/auth_manifests.yaml.j2
Labels: Libraries: OK

#360 fix: apply authorization policy to fix istio traffic issues
  charms/kfp-profile-controller/files/upstream/sync.py
Labels: Libraries: OK

#354 refactor: refactor env variables for kfp-api to match v2.0.2
  charms/kfp-api/src/charm.py
  charms/kfp-api/src/sample_config.json
  charms/kfp-api/tests/unit/test_operator.py
Labels: Libraries: OK

#331 feat: Update KFP charms for 1.8 release
  charms/kfp-api/config.yaml
  charms/kfp-api/metadata.yaml
  charms/kfp-api/src/templates/auth_manifests.yaml.j2
  charms/kfp-api/src/templates/ml-pipeline-service.yaml.j2
  charms/kfp-persistence/metadata.yaml
  charms/kfp-persistence/src/charm.py
  charms/kfp-persistence/src/templates/auth_manifests.yaml.j2
  charms/kfp-persistence/tests/unit/test_operator.py
  charms/kfp-profile-controller/files/upstream/sync.py
  charms/kfp-profile-controller/src/charm.py
  charms/kfp-profile-controller/src/components/pebble_components.py
  charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
  charms/kfp-profile-controller/src/templates/secrets.yaml.j2
  charms/kfp-profile-controller/tests/unit/test_operator.py
  charms/kfp-schedwf/metadata.yaml
  charms/kfp-schedwf/src/charm.py
  charms/kfp-schedwf/src/templates/auth_manifests.yaml.j2
  charms/kfp-ui/metadata.yaml
  charms/kfp-ui/src/charm.py
  charms/kfp-ui/src/components/pebble_components.py
  charms/kfp-ui/src/templates/auth_manifests.yaml.j2
  charms/kfp-ui/tests/unit/test_operator.py
  charms/kfp-viewer/metadata.yaml
  charms/kfp-viewer/src/charm.py
  charms/kfp-viewer/src/components/pebble_component.py
  charms/kfp-viewer/src/templates/auth_manifests.yaml.j2
  charms/kfp-viewer/tests/unit/test_operator.py
  charms/kfp-viz/metadata.yaml
  charms/kfp-viz/src/components/pebble_components.py
Labels: Libraries: OK

#361 fix: include namespace in metadata-grpc-service host name
  charms/kfp-profile-controller/src/charm.py
Labels: Libraries: OK
