Repository canonical/kfp-operators, pull requests merged in 2023-08, with the labels that each got.

#282 tests: remove wait for sidecar charms deployments to be ready and available
  tests/integration/test_kfp_functional.py
Labels: Libraries: OK

#268 Kf 3597 feat base class charm - kfp persistence
  .github/workflows/integrate.yaml
  charms/kfp-api/tests/integration/test_charm.py
  charms/kfp-persistence/charmcraft.yaml
  charms/kfp-persistence/metadata.yaml
  charms/kfp-persistence/requirements-integration.txt
  charms/kfp-persistence/requirements-unit.in
  charms/kfp-persistence/requirements-unit.txt
  charms/kfp-persistence/requirements.in
  charms/kfp-persistence/requirements.txt
  charms/kfp-persistence/src/charm.py
  charms/kfp-persistence/src/components/pebble_components.py
  charms/kfp-persistence/tests/integration/test_charm.py
  charms/kfp-persistence/tests/unit/test_operator.py
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
  tests/integration/bundles/kfp_latest_edge.yaml.j2
  tests/integration/helpers/bundle_mgmt.py
  tests/integration/test_kfp_functional.py
Labels: Libraries: OK

#280 feat: Rewrite the kfp-viewer charm following the sidecar pattern and using common base charm
  .gitignore
  charms/kfp-viewer/charmcraft.yaml
  charms/kfp-viewer/metadata.yaml
  charms/kfp-viewer/requirements-fmt.txt
  charms/kfp-viewer/requirements-integration.txt
  charms/kfp-viewer/requirements-lint.txt
  charms/kfp-viewer/requirements-unit.in
  charms/kfp-viewer/requirements-unit.txt
  charms/kfp-viewer/requirements.in
  charms/kfp-viewer/requirements.txt
  charms/kfp-viewer/src/charm.py
  charms/kfp-viewer/src/components/model_name_gate_component.py
  charms/kfp-viewer/src/components/pebble_component.py
  charms/kfp-viewer/src/templates/auth_manifests.yaml.j2
  charms/kfp-viewer/src/templates/crds.yaml.j2
  charms/kfp-viewer/tests/unit/test_operator.py
  charms/kfp-viewer/tox.ini
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
  tests/integration/bundles/kfp_latest_edge.yaml.j2
Labels: Libraries: OK

#284 update tox.ini's update-requirements
  charms/kfp-api/tox.ini
  charms/kfp-persistence/tox.ini
  charms/kfp-profile-controller/tox.ini
  charms/kfp-schedwf/tox.ini
  charms/kfp-ui/tox.ini
  charms/kfp-viewer/tox.ini
  charms/kfp-viz/tox.ini
  tox.ini
Labels: Libraries: OK

#279 fix: add ml-pipeline-service.yaml.j2 in K8S_RESOURCE_FILES (#255)
  charms/kfp-api/src/charm.py
  charms/kfp-api/src/templates/ml-pipeline-service.yaml.j2
Labels: Libraries: Out of sync, backport

#291 fix: Add fixes to rewrite kfp-viewer PR #280
  charms/kfp-viewer/src/charm.py
  charms/kfp-viewer/src/components/model_name_gate_component.py
  charms/kfp-viewer/src/components/pebble_component.py
  charms/kfp-viewer/tests/unit/test_operator.py
  tests/integration/bundles/kfp_latest_edge.yaml.j2
Labels: Libraries: OK

#296 Merge `KF-4149-dev-branch` into `main`
  .github/workflows/integrate.yaml
  charms/kfp-api/requirements-integration.txt
  charms/kfp-api/requirements-unit.txt
  charms/kfp-api/requirements.txt
  charms/kfp-api/src/charm.py
  charms/kfp-api/src/templates/ml-pipeline-service.yaml.j2
  charms/kfp-api/tests/integration/test_charm.py
  charms/kfp-persistence/requirements-integration.txt
  charms/kfp-persistence/requirements-unit.txt
  charms/kfp-persistence/requirements.in
  charms/kfp-persistence/requirements.txt
  charms/kfp-profile-controller/requirements-integration.txt
  charms/kfp-profile-controller/requirements-unit.txt
  charms/kfp-profile-controller/requirements.in
  charms/kfp-profile-controller/requirements.txt
  charms/kfp-schedwf/requirements-integration.txt
  charms/kfp-schedwf/requirements-unit.txt
  charms/kfp-schedwf/requirements.txt
  charms/kfp-ui/requirements-integration.txt
  charms/kfp-ui/requirements-unit.txt
  charms/kfp-ui/requirements.in
  charms/kfp-ui/requirements.txt
  charms/kfp-viewer/requirements-integration.txt
  charms/kfp-viewer/requirements-unit.txt
  charms/kfp-viewer/requirements.txt
  charms/kfp-viz/requirements-integration.txt
  charms/kfp-viz/requirements-unit.txt
  charms/kfp-viz/requirements.txt
Labels: Libraries: Out of sync

#264 Refactor kfp-ui to sidecar using the base charm
  charms/kfp-ui/charmcraft.yaml
  charms/kfp-ui/lib/charms/observability_libs/v1/kubernetes_service_patch.py
  charms/kfp-ui/metadata.yaml
  charms/kfp-ui/requirements-unit.in
  charms/kfp-ui/requirements-unit.txt
  charms/kfp-ui/requirements.in
  charms/kfp-ui/requirements.txt
  charms/kfp-ui/src/charm.py
  charms/kfp-ui/src/components/pebble_components.py
  charms/kfp-ui/src/templates/auth_manifests.yaml.j2
  charms/kfp-ui/src/templates/config.json
  charms/kfp-ui/src/templates/viewer-pod-template.json
  charms/kfp-ui/tests/unit/test_operator.py
  charms/kfp-ui/tox.ini
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
  tests/integration/bundles/kfp_latest_edge.yaml.j2
  tests/integration/conftest.py
Labels: Libraries: OK

#259 feat: get images script for track/2.0
  tools/get-images.sh
Labels: Libraries: Out of sync

#297 kfp-profile-controller Sidecar base charm implementation
  charms/kfp-profile-controller/charmcraft.yaml
  charms/kfp-profile-controller/metadata.yaml
  charms/kfp-profile-controller/requirements-unit.in
  charms/kfp-profile-controller/requirements-unit.txt
  charms/kfp-profile-controller/requirements.in
  charms/kfp-profile-controller/requirements.txt
  charms/kfp-profile-controller/src/charm.py
  charms/kfp-profile-controller/src/components/pebble_components.py
  charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
  charms/kfp-profile-controller/src/templates/secrets.yaml.j2
  charms/kfp-profile-controller/tests/integration/test_charm.py
  charms/kfp-profile-controller/tests/unit/test_operator.py
  tests/integration/bundles/kfp_latest_edge.yaml.j2
Labels: Libraries: OK

#294 Added docs links (KF-3970, KF-3971, KF-3972, KF-3973)
  charms/kfp-persistence/metadata.yaml
  charms/kfp-profile-controller/metadata.yaml
  charms/kfp-schedwf/metadata.yaml
  charms/kfp-viewer/metadata.yaml
Labels: Libraries: OK

#288 refactor: charmed-kubeflow-chisme's base charm to re-write kfp-schedwf
  charms/kfp-schedwf/metadata.yaml
  charms/kfp-schedwf/requirements-integration.in
  charms/kfp-schedwf/requirements-unit.in
  charms/kfp-schedwf/requirements-unit.txt
  charms/kfp-schedwf/requirements.in
  charms/kfp-schedwf/requirements.txt
  charms/kfp-schedwf/src/charm.py
  charms/kfp-schedwf/src/components/pebble_component.py
  charms/kfp-schedwf/src/templates/auth_manifests.yaml.j2
  charms/kfp-schedwf/src/templates/crds.yaml
  charms/kfp-schedwf/tests/unit/test_operator.py
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
  tests/integration/bundles/kfp_latest_edge.yaml.j2
Labels: Libraries: Out of sync

#299 ci: remove unsed step from integrate workflow
  .github/workflows/integrate.yaml
Labels: Libraries: OK

#272 fix: Handle relation-broken events
  charms/kfp-api/src/charm.py
  charms/kfp-api/tests/integration/test_charm.py
  charms/kfp-api/tests/unit/test_operator.py
Labels: Libraries: OK

#308 fix: profile-controller integration tests wait_for_idle
  charms/kfp-profile-controller/tests/integration/test_charm.py
Labels: Libraries: Out of sync

#309 feat: kfp-viz sidecar rewrite with base charm
  charms/kfp-viz/README.md
  charms/kfp-viz/lib/charms/observability_libs/v1/kubernetes_service_patch.py
  charms/kfp-viz/metadata.yaml
  charms/kfp-viz/requirements-unit.in
  charms/kfp-viz/requirements-unit.txt
  charms/kfp-viz/requirements.in
  charms/kfp-viz/requirements.txt
  charms/kfp-viz/src/charm.py
  charms/kfp-viz/src/components/pebble_components.py
  charms/kfp-viz/tests/unit/test_operator.py
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
  tests/integration/bundles/kfp_latest_edge.yaml.j2
Labels: Libraries: Out of sync
