Repository canonical/kfp-operators, pull requests merged in 2024-06, with the labels that each got.

#499 ci: bootstrap juju controller with agent version 3.5.0
  .github/workflows/integrate.yaml
Labels: Libraries: Out of sync

#486 fix: set correct default for custom_images in kfp-profile-controller
  charms/kfp-profile-controller/config.yaml
Labels: Libraries: Out of sync

#497 fix: handle incorrect custom images config
  charms/kfp-profile-controller/src/charm.py
  charms/kfp-profile-controller/tests/unit/test_operator.py
Labels: Libraries: OK

#500 ci: bootstrap juju controller with agent version 3.5.0 (#499)
  .github/workflows/integrate.yaml
Labels: Libraries: Out of sync, backport

#501 fix: Update KFP Controller Python image to Ubuntu/python rock
  charms/kfp-profile-controller/metadata.yaml
  charms/kfp-profile-controller/src/components/pebble_components.py
Labels: Libraries: Out of sync

#508 Add logging relation kfp-viz
  .github/workflows/integrate.yaml
  charms/kfp-viz/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kfp-viz/metadata.yaml
  charms/kfp-viz/requirements-integration.in
  charms/kfp-viz/requirements-integration.txt
  charms/kfp-viz/requirements-unit.txt
  charms/kfp-viz/requirements.in
  charms/kfp-viz/requirements.txt
  charms/kfp-viz/src/charm.py
  charms/kfp-viz/tests/integration/test_charm.py
  charms/kfp-viz/tests/unit/test_operator.py
Labels: Libraries: OK

#512 Add logging relation kfp-profile-controller
  charms/kfp-profile-controller/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kfp-profile-controller/metadata.yaml
  charms/kfp-profile-controller/requirements-integration.in
  charms/kfp-profile-controller/requirements-integration.txt
  charms/kfp-profile-controller/requirements-unit.txt
  charms/kfp-profile-controller/requirements.in
  charms/kfp-profile-controller/requirements.txt
  charms/kfp-profile-controller/src/charm.py
  charms/kfp-profile-controller/tests/integration/test_charm.py
  charms/kfp-profile-controller/tests/unit/test_operator.py
Labels: Libraries: Out of sync

#515 Reverting to use 8.0/stable for mysql-k8s
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
  tests/integration/bundles/kfp_1.8_stable_install.yaml.j2
  tests/integration/bundles/kfp_latest_edge.yaml.j2
Labels: bug, Libraries: Out of sync

#516 Reverting to use 8.0/stable for mysql-k8s
  tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
  tests/integration/bundles/kfp_1.8_stable_install.yaml.j2
  tests/integration/bundles/kfp_latest_edge.yaml.j2
Labels: Libraries: Out of sync

#496 Add logging relation kfp-metadate-writer
  .github/workflows/integrate.yaml
  charms/kfp-metadata-writer/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kfp-metadata-writer/metadata.yaml
  charms/kfp-metadata-writer/requirements-integration.in
  charms/kfp-metadata-writer/requirements-integration.txt
  charms/kfp-metadata-writer/requirements-unit.txt
  charms/kfp-metadata-writer/requirements.in
  charms/kfp-metadata-writer/requirements.txt
  charms/kfp-metadata-writer/src/charm.py
  charms/kfp-metadata-writer/tests/integration/test_charm.py
  charms/kfp-metadata-writer/tests/unit/test_operator.py
  charms/kfp-metadata-writer/tox.ini
Labels: Libraries: Out of sync

#505 Add logging relation kfp-api
  charms/kfp-api/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kfp-api/metadata.yaml
  charms/kfp-api/requirements-integration.in
  charms/kfp-api/requirements-integration.txt
  charms/kfp-api/requirements-unit.txt
  charms/kfp-api/requirements.txt
  charms/kfp-api/src/charm.py
  charms/kfp-api/tests/integration/test_charm.py
  charms/kfp-api/tests/unit/test_operator.py
Labels: Libraries: Out of sync

#511 Add logging relation kfp-ui
  .github/workflows/integrate.yaml
  charms/kfp-ui/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kfp-ui/metadata.yaml
  charms/kfp-ui/requirements-integration.in
  charms/kfp-ui/requirements-integration.txt
  charms/kfp-ui/requirements-unit.txt
  charms/kfp-ui/requirements.in
  charms/kfp-ui/requirements.txt
  charms/kfp-ui/src/charm.py
  charms/kfp-ui/tests/integration/bundle.yaml
  charms/kfp-ui/tests/integration/test_charm.py
  charms/kfp-ui/tests/unit/test_operator.py
Labels: Libraries: Out of sync

#509 Add logging relation kfp-viewer
  .github/workflows/integrate.yaml
  charms/kfp-viewer/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kfp-viewer/metadata.yaml
  charms/kfp-viewer/requirements-integration.in
  charms/kfp-viewer/requirements-integration.txt
  charms/kfp-viewer/requirements-unit.txt
  charms/kfp-viewer/requirements.in
  charms/kfp-viewer/requirements.txt
  charms/kfp-viewer/src/charm.py
  charms/kfp-viewer/tests/integration/test_charm.py
  charms/kfp-viewer/tests/unit/test_operator.py
Labels: Libraries: Out of sync

#513 Add logging relation kfp-schedwf
  .github/workflows/integrate.yaml
  charms/kfp-schedwf/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kfp-schedwf/metadata.yaml
  charms/kfp-schedwf/requirements-integration.in
  charms/kfp-schedwf/requirements-integration.txt
  charms/kfp-schedwf/requirements-unit.txt
  charms/kfp-schedwf/requirements.in
  charms/kfp-schedwf/requirements.txt
  charms/kfp-schedwf/src/charm.py
  charms/kfp-schedwf/tests/integration/test_charm.py
  charms/kfp-schedwf/tests/unit/test_operator.py
Labels: Libraries: OK

#518 ci: bump microk8s 1.25 -> 1.29
  .github/workflows/integrate.yaml
Labels: Libraries: OK

#519 build: bump ops to latest possible version
  charms/kfp-api/requirements-integration.txt
  charms/kfp-api/requirements-unit.txt
  charms/kfp-metadata-writer/requirements-integration.txt
  charms/kfp-persistence/requirements-integration.txt
  charms/kfp-profile-controller/requirements-integration.txt
  charms/kfp-profile-controller/requirements-unit.txt
  charms/kfp-schedwf/requirements-integration.txt
  charms/kfp-ui/requirements-integration.txt
  charms/kfp-viewer/requirements-integration.txt
  charms/kfp-viz/requirements-integration.txt
Labels: Libraries: OK

#522 ci: use juju 3.4/stable instead of 3.5/stable in track 2.0
  .github/workflows/integrate.yaml
Labels: Libraries: Out of sync

#523 build, tests: bump charmed-kubeflow-chisme 0.4.0 -> 0.4.1
  charms/kfp-api/requirements-integration.txt
  charms/kfp-metadata-writer/requirements-integration.txt
  charms/kfp-persistence/requirements-integration.txt
  charms/kfp-profile-controller/requirements-integration.txt
  charms/kfp-schedwf/requirements-integration.txt
  charms/kfp-ui/requirements-integration.txt
  charms/kfp-viewer/requirements-integration.txt
  charms/kfp-viz/requirements-integration.txt
Labels: Libraries: Out of sync
